name: Generate Action

on:
  workflow_dispatch:

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: create list
        run: make create-list VERSION=4.17.0

      - id: set-matrix
        run: echo "matrix=$(cat commands.json)" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: commands-4.17.0
          path: commands.json

  output:
    runs-on: ubuntu-latest
    needs: [ list ]
    strategy:
      matrix:
        commands: ${{ fromJSON(needs.list.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3

      - run: echo ${{ matrix.commands }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: PATH=$PATH:"$(pwd)" make generate VERSION=4.17.0 COMMAND="${{ matrix.commands }}"
