name: Update Generate Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '5 6 * * *'

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update Workflow
        run: ./scripts/get-latest-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: Automatic update to generate.yml
          committer: liquibot <liquibot@liquibase.org>
          author: liquibot <liquibot@liquibase.org>
          signoff: false
          branch: update/workflow
          delete-branch: true
          title: '[Automatic] Update generate.yml'
          body: |
            Automatic update to generate.yml
          draft: false
