name: Update Generate Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '5 6 * * *'

# Add permissions needed for the workflow
permissions:
  contents: write    # For checkout, pushing to repositories
  actions: read      # For workflow operations
  packages: write    # For package operations if needed
  id-token: write    # For authentication operations
  issues: write      # For creating issues if needed

jobs:
  update-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Workflow
        run: ./scripts/get-latest-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automatic update to generate.yml
          committer: liquibot <liquibot@liquibase.org>
          author: liquibot <liquibot@liquibase.org>
          signoff: false
          branch: update/workflow
          delete-branch: true
          title: '[Automatic] Update generate.yml'
          body: |
            Automatic update to generate.yml
          draft: false
